kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-team-web-read
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-read
subjects:
- kind: Group
  namespace: web
  name: 9e74b24f-b170-4f1a-8e14-e186d2fd964b
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-team-api-full
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-full
subjects:
- kind: Group
  namespace: api
  name: 9e74b24f-b170-4f1a-8e14-e186d2fd964b
