---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"tripviewer","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"tripviewer"}},"template":{"metadata":{"labels":{"app":"tripviewer"}},"spec":{"containers":[{"env":[{"name":"ALLOW_EMPTY_PASSWORD","value":"yes"},{"name":"USERPROFILE_API_ENDPOINT","value":"userprofile.default.svc.teamAKSClu-teamResources-679280"},{"name":"TRIPS_API_ENDPOINT","value":"trips.default.svc.teamAKSClu-teamResources-679280"}],"image":"registryojv0697.azurecr.io/tripinsights/tripviewer:latest","name":"tripviewer","ports":[{"containerPort":80,"name":"tripviewer"}],"resources":{"limits":{"cpu":"250m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}],"nodeSelector":{"kubernetes.io/os":"linux"}}}}}
  creationTimestamp: "2021-09-22T19:15:07Z"
  generation: 1
  name: tripviewer
  namespace: web
  resourceVersion: "20771"
  uid: 486e3475-961a-4c67-817d-3a3775e7e712
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tripviewer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tripviewer
    spec:
      containers:
      - env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: USERPROFILE_API_ENDPOINT
          value: http://userprofile
        - name: TRIPS_API_ENDPOINT
          value: http://trips
        image: registryojv0697.azurecr.io/tripinsights/tripviewer:latest
        imagePullPolicy: Always
        name: tripviewer
        ports:
        - containerPort: 80
          name: tripviewer
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
